//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finah_DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Newtonsoft.Json;


    public partial class answerlist
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int id { get; set; }
        public int list { get; set; }
        public int answer { get; set; }
        public int question { get; set; }
        public int workpoint { get; set; }
        public string hash { get; set; }
        public System.DateTime date { get; set; }
        public int usertype { get; set; }
        public int time { get; set; }
        [JsonIgnore]
        public virtual answer Answers { get; set; }
        [JsonIgnore]
        public virtual question Questions { get; set; }
    }
}
