//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finah_DomainClasses
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class answerlist
    {
        public long id { get; set; }
        public long list { get; set; }
        public long answer { get; set; }
        public long question { get; set; }
        public int workpoint { get; set; }
        public int user { get; set; }
        public int client { get; set; }
        [JsonIgnore]
        public virtual answer Answers { get; set; }
        [JsonIgnore]
        public virtual question Questions { get; set; }
    }
}
