//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finah_DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class time
    {
        public long id { get; set; }
        public System.DateTime datetime { get; set; }
        public int list { get; set; }
        public int time1 { get; set; }
        public int user { get; set; }
    }
}
