//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finah_DomainClasses
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class usertype
    {
        public usertype()
        {
            this.Users = new HashSet<user>();
        }
    
        public long id { get; set; }
        public string screenname { get; set; }
        public string description { get; set; }
        [JsonIgnore]
        public virtual ICollection<user> Users { get; set; }
    }
}
