//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_projectEntities : DbContext
    {
        public db_projectEntities()
            : base("name=db_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers1 { get; set; }
        public virtual DbSet<Answerlist> Answerlists1 { get; set; }
        public virtual DbSet<Question> Questions1 { get; set; }
        public virtual DbSet<Questionlist> Questionlists1 { get; set; }
        public virtual DbSet<Theme> Themes1 { get; set; }
        public virtual DbSet<Time> Times1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<Usertype> Usertypes1 { get; set; }
    }
}
