//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usertype
    {
        public Usertype()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string screenname { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
