//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.answerlist = new HashSet<Answerlist>();
            this.questionlist = new HashSet<Questionlist>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int theme { get; set; }
        public int choice { get; set; }
    
        public virtual ICollection<Answerlist> answerlist { get; set; }
        public virtual Theme theme1 { get; set; }
        public virtual ICollection<Questionlist> questionlist { get; set; }
    }
}
